// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcXZOfTJvZwEiVDcTNRkQfwtzqGck00Iw',
    appId: '1:400468902410:web:24c7f9e4ecfa4f5b5795f3',
    messagingSenderId: '400468902410',
    projectId: 'mynotes-ec52c',
    authDomain: 'mynotes-ec52c.firebaseapp.com',
    storageBucket: 'mynotes-ec52c.firebasestorage.app',
    measurementId: 'G-JHDVSVXYRJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBopDHjwVbvZSGcbnXrFlFtKHQdFfzq6mg',
    appId: '1:400468902410:android:16c43f7cc1652cb55795f3',
    messagingSenderId: '400468902410',
    projectId: 'mynotes-ec52c',
    storageBucket: 'mynotes-ec52c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbKnDohjEC40HfVE4qwCtu48pGa4GbtCA',
    appId: '1:400468902410:ios:c39af7ef4359eb425795f3',
    messagingSenderId: '400468902410',
    projectId: 'mynotes-ec52c',
    storageBucket: 'mynotes-ec52c.firebasestorage.app',
    iosBundleId: 'com.example.course',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbKnDohjEC40HfVE4qwCtu48pGa4GbtCA',
    appId: '1:400468902410:ios:c39af7ef4359eb425795f3',
    messagingSenderId: '400468902410',
    projectId: 'mynotes-ec52c',
    storageBucket: 'mynotes-ec52c.firebasestorage.app',
    iosBundleId: 'com.example.course',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcXZOfTJvZwEiVDcTNRkQfwtzqGck00Iw',
    appId: '1:400468902410:web:433155454d45875d5795f3',
    messagingSenderId: '400468902410',
    projectId: 'mynotes-ec52c',
    authDomain: 'mynotes-ec52c.firebaseapp.com',
    storageBucket: 'mynotes-ec52c.firebasestorage.app',
    measurementId: 'G-EQZ5BRSTJS',
  );
}
